services:
  game-server:
    image: ghcr.io/bourquejulien/cqi-2024-game-server-public:latest
    ports:
      - "5000:5000"
    networks:
      - game-network
    environment:
    # Swap to test offense or defense
      - OFFENSE_URL=http://bot:5000
      - DEFENSE_URL=http://your_bot:5000
      # - SEED=42 # Optional seed for reproducibility
      # - MAX_MOVE=200 # Optional max move for the game
  bot:
    image: ghcr.io/bourquejulien/cqi-2024-easy-bot:latest
    hostname: bot
    networks:
      - game-network
    environment:
      - PORT=5000
  your_bot:
    hostname: your_bot
    build:
      context: .
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
