services:
  game-server:
    image: ghcr.io/bourquejulien/cqi-2024-game-server:latest
    ports:
      - "5000:5000"
    networks:
      - game-network
    environment:
      - BOT_1_URL=http://bot_1:5000
      - BOT_2_URL=http://bot_2:5000
  bot-1:
    hostname: bot_1
    networks:
      - game-network
    environment:
      - PORT=5000
  bot-2:
    hostname: bot_2
    build:
      context: .
      dockerfile: ./bot/Dockerfile
      target: final
    networks:
      - game-network
    environment:
      - PORT=5000

networks:
  game-network:
    driver: bridge
