services:
  main_server:
    image: ghcr.io/bourquejulien/cqi-2024-main-server:latest
    restart: unless-stopped
    container_name: main_server
    ports:
      - "8000:8000"

volumes:
  postgres_data:
