services:
  game_runner:
    restart: unless-stopped
    image: ghcr.io/bourquejulien/cqi-2024-game-runner:latest
    container_name: game_runner

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/root/.docker/config.json:ro
    network_mode: "host"
