services:
  game-server:
    environment:
      - MODE=public
      - OFFENSE_URL=http://bot_1:5001
      - DEFENSE_URL=http://bot_2:5002
  bot-1:
    hostname: bot_1
    build:
      args:
        USE_PYARMOR: false
      context: .
      dockerfile: ./bot/Dockerfile
      target: final
    networks:
      - game-network
    environment:
      - PORT=5001
  bot-2:
    hostname: bot_2
    build:
      args:
        USE_PYARMOR: false
      context: .
      dockerfile: ./bot/Dockerfile
      target: final
    networks:
      - game-network
    environment:
      - PORT=5002
