services:
  game-server:
    image: brqu/cqi-game-server:latest
    build:
      args:
        USE_PYARMOR: false
      context: .
      dockerfile: ./game_server/Dockerfile
      target: final
    ports:
      - "5000:5000"
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
