name: Publish Bots

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
    - "cqi/bot/**"
    - "cqi/game_server_common/**"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push easy bot
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./cqi
          file: ./cqi/bot/Dockerfile
          push: true
          build-args: |
            USE_PYARMOR=true
            BOT_LEVEL=easy
          tags: |
            ghcr.io/${{ github.repository }}-easy-bot:latest

      - name: Build and push medium bot
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./cqi
          file: ./cqi/bot/Dockerfile
          push: true
          build-args: |
            USE_PYARMOR=false
            BOT_LEVEL=medium
          tags: |
            ghcr.io/${{ github.repository }}-medium-bot:latest
