name: Publish Main Server

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
    - "cqi/main_server/**"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./cqi/main_server
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-gamer-server:latest
            ghcr.io/${{ github.repository }}-gamer-server:${{ github.sha }}
